/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2023-06-02-c386555f9c"
#endif /* AVUTIL_FFVERSION_H */
