/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2023-03-03-7c0986a697"
#endif /* AVUTIL_FFVERSION_H */
